sudo: required
services:
  - docker
before_install:
  - docker build -t pankajsa/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true pankajsa/react-test yarn run test -- --coverage
after_success:
  - docker build -t pankajsa/multi-client ./client
  - docker build -t pankajsa/multi-nginx ./nginx
  - docker build -t pankajsa/multi-server ./server
  - docker build -t pankajsa/multi-worker ./worker
  #login to docker hub
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  #publish images to hub
  - docker push pankajsa/multi-client
  - docker push pankajsa/multi-nginx
  - docker push pankajsa/multi-server
  - docker push pankajsa/multi-worker
